### ISSUE TITLE
Cannot change citation style

### ISSUE THREAD

**Issue by fruitdumonde** [krassowski/jupyterlab-citation-manager#29] opened 2021-08-06 17:05 UTC
I installed the citation manger with command python3 -m pip install --user jupyterlab-citation-manager. After creating a new notebook in Jupyterlab and adding a citation and bibliography I was not able to change the style by clicking on the palette icon in the sidebar or pressing Alt+s. No window opened to choose a style.

I then searched for the location of the .csl files on the server, but there was only one in an unexpected folder:
![grafik](https://user-images.githubusercontent.com/55314929/128546471-c6549b7a-a703-49d4-a8a9-adf37c424df6.png)

I then followed the steps to add custom styles and placed the whole CSL repository in ~/.local/share/jupyter/csl-styles and restarted the Jupyter instance. It is still not possible to select a style.

Jupyterlab version is 3.1.1

**Comment by krassowski** [comment] 2021-08-06 17:25
Thank you for checking out this extension!

Could you please paste the output of the following three commands?

```bash
jupyter --path
```

```bash
jupyter server extension list
```

```bash
jupyter serverextension list
```

And check whether there are any errors in the browser developer console (see [here](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools#How_to_open_the_devtools_in_your_browser) for instructions on opening it).

**Comment by krassowski** [comment] 2021-08-06 17:49
I see that the csl-styles did not get uploaded on the PyPI in versions 0.1.1 and 0.1.2 (but there were fine in 0.1.0) - I think I know where the problems is. I do not understand why this would not work for you locally though.

**Comment by fruitdumonde** [comment] 2021-08-06 18:02
**Output of jupyter --path**
➜  ~ jupyter --path
config:
    /home/<username>/.jupyter
    /usr/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/<username>/.local/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /home/<username>/.local/share/jupyter/runtime

**Output of jupyter server extension list**
Config dir: /home/<username>/.jupyter

Config dir: /usr/etc/jupyter

Config dir: /usr/local/etc/jupyter

Output of jupyter serverextension list is empty.


The developer console shows a JSON parsing error whenever I click on the palette symbol, but I can't figure out what the actual JSON data is.
![grafik](https://user-images.githubusercontent.com/55314929/128552321-804c1e04-2797-4b2e-bf65-407814e96078.png)

Note that Jupyter is not running on my local computer, but on a remote server and I'm only able to write files inside my home directory (and below).

**Comment by krassowski** [comment] 2021-08-06 18:27
> Note that Jupyter is not running on my local computer, but on a remote server and I'm only able to write files inside my home directory (and below).

Are you using JupyterHub?

> Output of jupyter server extension list
> Config dir: /home//.jupyter
>
> Config dir: /usr/etc/jupyter
> 
> Config dir: /usr/local/etc/jupyter
> 
> Output of jupyter serverextension list is empty.

As none of this contain this extension this indicates that the server extension did not get properly installed. I wonder if this was because of the `--user` flag. Please try running:

```
jupyter server extension enable jupyterlab_citation_manager
```

or, if using JupyterHub:

```
jupyter serverextension enable jupyterlab_citation_manager
```

If this command succeeds (you don't need to run both, just one that is relevant to your server type, see [this](https://stackoverflow.com/questions/67797152/what-is-the-difference-between-jupyter-notebook-and-jupyter-server/67804732#67804732)), please restart JupyterLab (and this means restarting it on the remote server!) and see if it works now.

**Comment by krassowski** [comment] 2021-08-19 14:26
Hi @fruitdumonde could please you try installing:

```bassh
pip install jupyterlab-citation-data==0.1
```

and see if you get the extra styles after restarting JuypterLab?

**Comment by krassowski** [comment] 2021-08-30 16:39
I will close this issue as I believe it is now resolved, but if the problem is still happening, please reopen and provide additional details so I can investigate. Thank you!

**Closed by krassowski** 2021-08-30 16:39 UTC
Labels: bug
